### ISSUE TITLE
Cannot disable sticky navigation

### ISSUE THREAD

**Issue by ploebb** [microweber-templates/new-world#6]
The option to disable sticky navigation does not "stick" ;-)
After reloading, the option switches back to "yes". I just tried with a fresh install:

- cPanel with softaculous
- microweber 1.2.6
- New World 2.5

![grafik](https://user-images.githubusercontent.com/5870131/117578812-78c8d780-b0f0-11eb-9f94-efceccf41226.png)

**Comment by peter-mw** [comment]
fixed
