### ISSUE TITLE
Changing the direction of the text in the Arabic language starts from the right

### ISSUE THREAD

**Issue by mmegahed3046** [microweber-templates/new-world#9]
![2022-03-29_16-52-51](https://user-images.githubusercontent.com/30393589/160640686-dd35c8d4-19d1-4b45-8123-4b99df4e0006.png)

![2022-03-29_16-53-20](https://user-images.githubusercontent.com/30393589/160640694-6022d80a-3aa4-493e-91ca-65307000e940.png)

in mobile
![2022-03-29_16-51-19](https://user-images.githubusercontent.com/30393589/160640879-5cf01752-7e3f-47b4-b82b-c7bae98b6cc6.png)

**Comment by peter-mw** [comment]
fixed in this commit https://github.com/microweber-templates/new-world/commit/065bcc5470a5dfa011ce5547d4d5e4ff48a7272c
